mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^test$', views.test),
	url(r'^monitor$', views.monitor),
]

polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


sex_choices = (
	('f', 'famale'),
	('m', 'male'),
)


class User(models.Model):
	name = models.CharField(max_length=30)
	sex = models.CharField(max_length=1, choices=sex_choices)

	def __str__(self):
		return self.name


class IP_address(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class status(models.Model):
	name = models.CharField(max_length=10000)
	IP_addresses = models.ManyToManyField(IP_address)

	def __str__(self):
		return self.name

polls/views.py
from django.shortcuts import render_to_response
from polls.models import IP_address, status 
from django.http import HttpResponse

# Create your views here.


def monitor(request):
	IP_addresses = IP_address.objects.all()
	return render_to_response('monitor.html',{'IP_addresses':IP_addresses})



def test(request):
	return render_to_response('test.html') 

polls/templates/index.html
{% for ip_address in IP_addresses %}
<div>
	<h3> {{ ip_address.name }} </h3>
	{% for status in ip_address.status_set.all %}
	<li>{{status}}</li>
	{% endfor %}
</div>
{% endfor %}

polls/templates/monitor.html
{% for ip_address in IP_addresses %}
<div>
	<h3> {{ ip_address.name }} </h3>
	{% for status in ip_address.status_set.all %}
	<li>{{status}}</li>
	{% endfor %}
</div>
{% endfor %}

polls/templates/test.html
Description              size (kB)            Used       Available Used%
Physical memory            2043048          721860         1321188   35%
Virtual memory             6139044          721860         5417184   11%
Memory buffers             2043048             816         2042232    0%
Cached memory               284676          284676               0  100%
Shared memory                 9148            9148               0  100%
Swap space                 4095996               0         4095996    0%
/                         10229760         4314432         5915328   42%
/dev/shm                   1021524              80         1021444    0%
/run                       1021524            9064         1012460    0%
/sys/fs/cgroup             1021524               0         1021524    0%
/boot                      5109760          125484         4984276    2%HOST-RESOURCES-MIB::hrMemorySize.0 = INTEGER: 2043048 KBytesIP-MIB::ipAdEntAddr.127.0.0.1 = IpAddress: 127.0.0.1
IP-MIB::ipAdEntAddr.192.168.1.252 = IpAddress: 192.168.1.252
IP-MIB::ipAdEntIfIndex.127.0.0.1 = INTEGER: 1
IP-MIB::ipAdEntIfIndex.192.168.1.252 = INTEGER: 2
IP-MIB::ipAdEntNetMask.127.0.0.1 = IpAddress: 255.0.0.0
IP-MIB::ipAdEntNetMask.192.168.1.252 = IpAddress: 255.255.255.0
IP-MIB::ipAdEntBcastAddr.127.0.0.1 = INTEGER: 0
IP-MIB::ipAdEntBcastAddr.192.168.1.252 = INTEGER: 1SNMPv2-MIB::sysDescr.0 = STRING: Linux client 3.10.0-123.el7.x86_64 #1 SMP Mon May 5 11:16:57 EDT 2014 x86_64
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (4959) 0:00:49.59
SNMPv2-MIB::sysContact.0 = STRING: Root <root@localhost> (configure /etc/snmp/snmp.local.conf)
SNMPv2-MIB::sysName.0 = STRING: client
SNMPv2-MIB::sysLocation.0 = STRING: Unknown (edit /etc/snmp/snmpd.conf)
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORID.1 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.2 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.5 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.6 = OID: IP-MIB::ip
SNMPv2-MIB::sysORID.7 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.8 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
SNMPv2-MIB::sysORID.10 = OID: NOTIFICATION-LOG-MIB::notificationLogMIB
SNMPv2-MIB::sysORDescr.1 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.2 = STRING: The management information definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORDescr.3 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.5 = STRING: The MIB module for managing TCP implementations
SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing IP and ICMP implementations
SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing UDP implementations
SNMPv2-MIB::sysORDescr.8 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP Notification, plus filtering.
SNMPv2-MIB::sysORDescr.10 = STRING: The MIB module for logging SNMP Notifications.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.6 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.7 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.8 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.9 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.10 = Timeticks: (2) 0:00:00.02IF-MIB::ifDescr.1 = STRING: lo
IF-MIB::ifDescr.2 = STRING: eno16777736Description              size (kB)            Used       Available Used%
Physical memory            2043048          722040         1321008   35%
Virtual memory             6139044          722040         5417004   11%
Memory buffers             2043048             816         2042232    0%
Cached memory               284740          284740               0  100%
Shared memory                 9148            9148               0  100%
Swap space                 4095996               0         4095996    0%
/                         10229760         4314172         5915588   42%
/dev/shm                   1021524              80         1021444    0%
/run                       1021524            9064         1012460    0%
/sys/fs/cgroup             1021524               0         1021524    0%
/boot                      5109760          125484         4984276    2%